//! Hierarchical (multi-sheet) netlist ingestion, against the real EdgeBoard
//! export.
//!
//! # Fixture provenance
//!
//! `fixtures/mad_edge.net` is a `kicad-cli sch export netlist` of the MaD
//! repo's `Hardware/EdgeBoard/KiCad/MaD_Edge.kicad_sch` (three hierarchical
//! sheets: the root plus `MaD_Edge_Sheet2` and `MaD_Edge_Sheet3`), taken
//! 2026-07-26 with Eeschema 9.0.6 — export version `"E"`, 168 components,
//! 243 nets, 718 nodes. The file carries the same provenance as a `;` comment
//! header, which the parser skips wherever whitespace is legal.
//!
//! The export is **not byte-stable**: `(design (source …))` is an absolute
//! path and `(date …)` is the export timestamp, so a regeneration check
//! compares the parsed *shape* asserted here — counts, membership, sheet
//! paths — never bytes. `tests/fixture_smoke.rs` holds the cheap text-level
//! landmarks; this binary holds the parse-level truth.
//!
//! Why a second fixture at all: `ds2_addon.net` is flat, so it cannot
//! exercise sheet-scoped net names, per-component sheet paths, an 80-pin edge
//! connector, or an empty libsource lib name. All four appear here.

use std::collections::{HashMap, HashSet};

use rstest::rstest;

use embsim_board::netlist::{
    is_autogenerated_net_name, net_sheet_path, net_short_label, normalize_pin_name, parse,
};
use embsim_board::{Board, ParsedNetlist, PartRegistry};

const MAD_EDGE: &str = include_str!("fixtures/mad_edge.net");

/// Component count of the committed export.
const EXPECTED_COMPONENTS: usize = 168;
/// Net count of the committed export.
const EXPECTED_NETS: usize = 243;
/// Total `(node …)` membership entries of the committed export.
const EXPECTED_NODES: usize = 718;
/// Nets whose name is sheet-scoped (a local label on a sub-sheet).
const EXPECTED_SHEET_SCOPED_NETS: usize = 53;

fn edge() -> ParsedNetlist {
    parse(MAD_EDGE).expect("the EdgeBoard fixture parses")
}

// ============================================================
// Shape
// ============================================================

#[rstest]
fn mad_edge_parses_with_the_exported_shape() {
    let parsed = edge();
    assert_eq!(parsed.version, "E");
    assert_eq!(parsed.components.len(), EXPECTED_COMPONENTS);
    assert_eq!(parsed.nets.len(), EXPECTED_NETS);
    assert_eq!(
        parsed.nets.iter().map(|n| n.nodes.len()).sum::<usize>(),
        EXPECTED_NODES
    );
}

/// The provenance header is a `;` comment block, and its presence must not
/// change what the parser sees.
#[rstest]
fn fixture_carries_a_provenance_header_the_parser_skips() {
    assert!(
        MAD_EDGE.starts_with("; embsim-board netlist fixture"),
        "the committed fixture must keep its provenance header"
    );
    assert!(MAD_EDGE.contains("kicad-cli sch export netlist"));
    let stripped: String = MAD_EDGE
        .lines()
        .skip_while(|l| l.starts_with(';'))
        .collect::<Vec<_>>()
        .join("\n");
    assert_eq!(parse(&stripped).unwrap(), edge());
}

// ============================================================
// Membership is lossless
// ============================================================

/// Every net node names a declared component, every declared component owns
/// at least one node, and no pin appears on two nets — i.e. the parsed graph
/// can be walked back to the same membership the export describes.
#[rstest]
fn membership_round_trips_against_the_component_list() {
    let parsed = edge();

    let declared: HashSet<&str> = parsed
        .components
        .iter()
        .map(|c| c.reference.as_str())
        .collect();
    assert_eq!(declared.len(), EXPECTED_COMPONENTS, "references are unique");

    let mut pins_by_ref: HashMap<&str, HashSet<&str>> = HashMap::new();
    let mut owner_of_pin: HashMap<(&str, &str), &str> = HashMap::new();
    for net in &parsed.nets {
        for node in &net.nodes {
            assert!(
                declared.contains(node.reference.as_str()),
                "net {:?} references undeclared component {:?}",
                net.name,
                node.reference
            );
            assert!(
                pins_by_ref
                    .entry(node.reference.as_str())
                    .or_default()
                    .insert(node.pin.as_str()),
                "{}.{} appears twice",
                node.reference,
                node.pin
            );
            let previous =
                owner_of_pin.insert((node.reference.as_str(), node.pin.as_str()), &net.name);
            assert_eq!(
                previous, None,
                "{}.{} is a member of two nets",
                node.reference, node.pin
            );
        }
    }

    assert_eq!(owner_of_pin.len(), EXPECTED_NODES);
    let unwired: Vec<&str> = declared
        .iter()
        .copied()
        .filter(|r| !pins_by_ref.contains_key(r))
        .collect();
    assert!(
        unwired.is_empty(),
        "components with no net membership: {unwired:?}"
    );
}

/// J3 is the P2 Edge module socket — all 80 edge fingers must land in the
/// graph (the module's own netlist calls the mating connector J203).
#[rstest]
fn edge_module_socket_keeps_all_eighty_fingers() {
    let parsed = edge();
    let socket = parsed
        .components
        .iter()
        .find(|c| c.reference == "J3")
        .expect("J3 present");
    assert_eq!(socket.part, "P2_EDGE_MODULE_SOCKET");

    let pins: HashSet<&str> = parsed
        .nets
        .iter()
        .flat_map(|n| n.nodes.iter())
        .filter(|n| n.reference == "J3")
        .map(|n| n.pin.as_str())
        .collect();
    assert_eq!(pins.len(), 80);
}

// ============================================================
// Sheet-scoped net names
// ============================================================

/// Sheet-scoped names keep their full path, and the two sub-sheets are the
/// only scopes in play.
#[rstest]
fn sheet_scoped_net_names_keep_their_full_path() {
    let parsed = edge();

    let scoped: Vec<&str> = parsed
        .nets
        .iter()
        .map(|n| n.name.as_str())
        .filter(|n| net_sheet_path(n).is_some())
        .collect();
    assert_eq!(scoped.len(), EXPECTED_SHEET_SCOPED_NETS);

    let paths: HashSet<&str> = scoped.iter().filter_map(|n| net_sheet_path(n)).collect();
    assert_eq!(
        paths,
        HashSet::from(["/MaD_Edge_Sheet2/", "/MaD_Edge_Sheet3/"])
    );

    // Landmarks: the isolated force-gauge UART on sheet 2 and the servo pulse
    // pair on sheet 3.
    let ifg_rx = parsed
        .nets
        .iter()
        .find(|n| n.name == "/MaD_Edge_Sheet2/IFG_RX")
        .expect("sheet-2 IFG_RX present");
    assert_eq!(net_short_label(&ifg_rx.name), "IFG_RX");
    assert_eq!(ifg_rx.nodes.len(), 2);
    assert!(parsed
        .nets
        .iter()
        .any(|n| n.name == "/MaD_Edge_Sheet3/SC_PUL+"));

    // Global labels and power nets stay unscoped.
    for global in ["GND", "+3.3V", "+5V", "RESn", "P16"] {
        let net = parsed
            .nets
            .iter()
            .find(|n| n.name == global)
            .unwrap_or_else(|| panic!("{global} present"));
        assert_eq!(net_sheet_path(&net.name), None);
    }
}

/// Names are unique *as canonical strings*; leaf labels are not required to
/// be. (In this board no two sheets happen to reuse a leaf, so the
/// same-leaf-collision case is covered by the synthetic netlist in
/// `netlist.rs`'s unit tests and by `board_build_keeps_same_leaf_nets_distinct`
/// below.)
#[rstest]
fn canonical_net_names_are_unique() {
    let parsed = edge();
    let names: HashSet<&str> = parsed.nets.iter().map(|n| n.name.as_str()).collect();
    assert_eq!(names.len(), EXPECTED_NETS);
}

/// KiCad's synthesized names: 65 `Net-(…)` unlabeled nets and 47
/// `unconnected-(…)` stubs, every stub a single pin the schematic marks
/// no-connect.
#[rstest]
fn autogenerated_names_describe_single_pin_no_connect_stubs() {
    let parsed = edge();

    let unconnected: Vec<_> = parsed
        .nets
        .iter()
        .filter(|n| n.name.starts_with("unconnected-("))
        .collect();
    assert_eq!(unconnected.len(), 47);
    for net in &unconnected {
        assert!(is_autogenerated_net_name(&net.name));
        assert_eq!(net.nodes.len(), 1, "{} should be a stub", net.name);
        let pintype = net.nodes[0]
            .pintype
            .as_deref()
            .unwrap_or_else(|| panic!("{} node carries a pintype", net.name));
        assert!(
            pintype.contains("no_connect"),
            "{} node pintype {pintype:?} should be a no-connect",
            net.name
        );
    }

    assert_eq!(
        parsed
            .nets
            .iter()
            .filter(|n| n.name.starts_with("Net-("))
            .count(),
        65
    );
}

// ============================================================
// Component-side hierarchy
// ============================================================

/// Every component carries the sheet instance it was placed on.
#[rstest]
#[case::root("/", 21)]
#[case::sheet2("/MaD_Edge_Sheet2/", 101)]
#[case::sheet3("/MaD_Edge_Sheet3/", 46)]
fn component_sheetpaths_distribute_across_three_sheets(
    #[case] sheetpath: &str,
    #[case] expected: usize,
) {
    let parsed = edge();
    assert_eq!(
        parsed
            .components
            .iter()
            .filter(|c| c.sheetpath == sheetpath)
            .count(),
        expected
    );
}

/// Overline pinfunctions from the real export normalize to one spelling.
#[rstest]
#[case::gate("U24", "12", "~G")]
#[case::enable("U1", "4", "~ON")]
fn overline_pinfunctions_normalize(
    #[case] reference: &str,
    #[case] pin: &str,
    #[case] expected: &str,
) {
    let parsed = edge();
    let node = parsed
        .nets
        .iter()
        .flat_map(|n| n.nodes.iter())
        .find(|n| n.reference == reference && n.pin == pin)
        .unwrap_or_else(|| panic!("{reference}.{pin} present"));
    let function = node.pinfunction.as_deref().expect("pinfunction present");
    assert_eq!(normalize_pin_name(function), expected);
}

/// A project-local / cached symbol exports with an empty libsource lib —
/// classification keys on `part`, so this must not be an error.
#[rstest]
fn empty_libsource_lib_names_survive_parsing() {
    let parsed = edge();
    let ic6 = parsed
        .components
        .iter()
        .find(|c| c.reference == "IC6")
        .expect("IC6 present");
    assert_eq!(ic6.lib, "");
    assert_eq!(ic6.part, "NSI50010YT1G_1");
    assert!(parsed.components.iter().all(|c| !c.part.is_empty()));
}

/// No component in this export sets the KiCad `dnp` property or the
/// `value == "X"` convention — the whole board is fitted, so a future DNP
/// regression here is visible.
#[rstest]
fn the_edgeboard_export_has_no_dnp_components() {
    let parsed = edge();
    assert!(parsed.components.iter().all(|c| !c.dnp && c.value != "X"));
}

// ============================================================
// Board build
// ============================================================

/// The canonical name reaches the built board: two sheets both labelled
/// `SIGNAL` stay two nets with two distinguishable names.
#[rstest]
fn board_build_keeps_same_leaf_nets_distinct() {
    const TWO_SHEETS: &str = r#"(export (version "E")
        (components
          (comp (ref "R1") (value "10k")
            (libsource (lib "Device") (part "R_Small"))
            (sheetpath (names "/Sheet2/") (tstamps "/1111/")))
          (comp (ref "R2") (value "10k")
            (libsource (lib "Device") (part "R_Small"))
            (sheetpath (names "/Sheet3/") (tstamps "/2222/"))))
        (nets
          (net (code "1") (name "/Sheet2/SIGNAL")
            (node (ref "R1") (pin "1") (pintype "passive")))
          (net (code "2") (name "/Sheet3/SIGNAL")
            (node (ref "R2") (pin "1") (pintype "passive")))
          (net (code "3") (name "/Sheet2/~{OE}")
            (node (ref "R1") (pin "2") (pintype "passive"))
            (node (ref "R2") (pin "2") (pintype "passive")))))"#;

    let board = Board::from_netlist(parse(TWO_SHEETS).unwrap(), &PartRegistry::new())
        .expect("two resistors on three nets build");

    let names: Vec<&str> = board.nets().iter().map(|n| n.name.as_str()).collect();
    assert_eq!(names, ["/Sheet2/SIGNAL", "/Sheet3/SIGNAL", "/Sheet2/~OE"]);
    assert_eq!(board.nets()[0].nodes.len(), 1);
    assert_eq!(board.nets()[2].nodes.len(), 2);
}
